#!/bin/bash
sudo su                                                                                     #Elevates permissions.
yum -y install httpd mod_ssl                                                                #installs the necessary components.
systemctl enable httpd
systemctl start httpd

sed -i 's/^/#/g' /etc/httpd/conf.d/welcome.conf                                             #Comments out the entirety of welcome.conf.

echo -e "<html> \n<h1> Welcome, NTI-300 </h1> \n</html>" > /var/www/html/index.html         #Creates a new basic index page with given text.
