#!/bin/bash
sudo -u 
yum install python-pip -y                                           #Using Gcloud.
pip install virtualenv
pip install --upgrade pip                                         #Why doesn't this download the latest by default?
mkdir /opt/django
cd /opt/django

yum install epel-release -y
yum install python34 python-pip -y                                   #Upgrades python.

virtualenv -p python3 django
cd django
source bin/activate

pip install django
django-admin startproject project1

cd ..                                                              #Isn't in the right directory by default for this operation.
sudo chown -R tjense04 django
yum install git -y


myip-$=( curl https://api.ipfy.org )                                 #Gets global IP address and stores it.
sed -i “s/ALLOWED_HOSTS = \[\]/ALLOWED_HOSTS =  \[‘“$myip”’\]/g” /opt/django/django/project1/project1/settings.py 

#
#
#

sudo -u tjense04 /opt/django/django/project1/manage.py runserver 0.0.0.0:8000&
